stages:
  - prebuild
  - build
  - test
  - publish

.docker-vars:
  variables:
    CI_IMAGE_TAG: 0.0.4

.run-in-docker:
  extends: .docker-vars
  tags:
    - linux
    - docker
#  services:
    # configure a registry mirror https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#    - docker:dind

.build-docker:
  extends: .docker-vars
  tags:
    - linux
    - docker-host
  before_script:
    - echo $CI_PIPELINE_SOURCE $CI ${CI_COMMIT_REF_SLUG} $CI_REGISTRY_IMAGE
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY


.build_and_push: &build-and-push
  - export DOCKER_IMAGE=$CI_REGISTRY_IMAGE/$IMAGE_NAME:$DOCKER_IMAGE_TAG
  - echo Building $DOCKER_IMAGE from $DOCKER_FILE
  - docker build --pull -t $DOCKER_IMAGE --build-arg DOCKER_IMAGE_TAG -f $DOCKER_FILE .
  - docker push $DOCKER_IMAGE


build-docker-ci:
  extends: .build-docker
  image: docker:latest
  stage: prebuild
  script:
    - cd docker
    - export DOCKER_FILE=Dockerfile.CI
    - export IMAGE_NAME=docker-ci
    - export DOCKER_IMAGE_TAG=${CI_IMAGE_TAG}
    - *build-and-push
  only:
    changes:
      - .gitlab-ci.yml
      - docker/Dockerfile.CI


build-cpp-lib-linux:
  extends: .run-in-docker
  stage: build
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - cmake -B oos -DCMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=oos/install -DCMAKE_GENERATOR=Ninja -DCPACK_GENERATOR=DEB $EXTRA_PARAMS cpp-src
    - cd oos
    - ninja
    - ninja install
    - ninja package
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - ninja
    - ninja install
  artifacts:
    paths:
      - oos/install
      - oos/bin
      - oos/click*Linux.deb
      - oos/protobuf-gen/Messaging*

build-shared-cpp-lib-linux:
  extends: build-cpp-lib-linux
  variables:
    EXTRA_PARAMS: "-DBUILD_SHARED_LIBS=ON"

.test-cpp-lib-linux:
  extends: .run-in-docker
  stage: test
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - oos/bin/click-tests --reporter junit --out catch2-junit.xml

  artifacts:
    when: always
    reports:
      junit: catch2-junit.xml

test-cpp-lib-linux:
  extends: .test-cpp-lib-linux
  needs:
    - job: build-cpp-lib-linux
      artifacts: true

test-shared-cpp-lib-linux:
  extends: .test-cpp-lib-linux
  variables:
    LD_LIBRARY_PATH: "${CI_PROJECT_DIR}/oos/install/lib"
  needs:
    - job: build-shared-cpp-lib-linux
      artifacts: true

.publish-cpp-lib-linux:
  extends: .run-in-docker
  stage: publish
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - PACKAGE_VERSION=$CI_COMMIT_TAG
    - grep "click VERSION $PACKAGE_VERSION" cpp-src/CMakeLists.txt
    - cd oos
    - PACKAGE_NAME=`ls click-*.deb`
    - echo Publishing $PACKAGE_NAME as ${PACKAGE_VERSION}/${PACKAGE_UPLOAD_NAME} and latest/${PACKAGE_UPLOAD_NAME}
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $PACKAGE_NAME "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/click/${PACKAGE_VERSION}/${PACKAGE_UPLOAD_NAME}"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $PACKAGE_NAME "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/click/latest/${PACKAGE_UPLOAD_NAME}"'
    # Publish click to conan.algoryx.se
    - cd ../cpp-src/click
    - conan create . algoryx/stable -pr:b=default
    - conan user $CONAN_USERNAME -p $CONAN_PASSWORD -r algoryx
    - conan upload --all click/${PACKAGE_VERSION}@algoryx/stable

  only:
    - tags

publish-cpp-lib-linux:
  extends: .publish-cpp-lib-linux
  variables:
    PACKAGE_UPLOAD_NAME: click-static-focal-amd64.deb
  needs:
    - job: build-cpp-lib-linux
      artifacts: true

publish-shared-cpp-lib-linux:
  extends: .publish-cpp-lib-linux
  variables:
    PACKAGE_UPLOAD_NAME: click-shared-focal-amd64.deb
  needs:
    - job: build-shared-cpp-lib-linux
      artifacts: true

test-python-lib:
  extends: .run-in-docker
  stage: test
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - cd python-src
    - (poetry install && poetry run pytest --junitxml=pclick-junit.xml)
  artifacts:
    when: always
    reports:
      junit: pclick-junit.xml

.publish-python-lib:
  extends: .run-in-docker
  stage: publish
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - cd $PYTHONDIR
    - poetry publish --build --username=__token__ --password=${pypi_password}
  only:
    - tags

publish-pclick:
  extends: .publish-python-lib
  variables:
    PYTHONDIR: python-src

.build-test-cpp-lib-windows:
  stage: build
  tags:
    - windows
    - x64
    - vs2019
  variables:
    # Use project specific conan directory to cache between builds but not between projects
    CONAN_USER_HOME: $CI_BUILDS_DIR/conan-ci/$CI_PROJECT_PATH_SLUG
  script:
    - mkdir oos
    - cd oos
    - cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX=./install -G "Visual Studio 16 2019" -A $TARGET_ARCH $EXTRA_PARAMS ../cpp-src
    - cmake --build . --target INSTALL --config Debug
    - cmake -D CMAKE_BUILD_TYPE=Release .
    - cmake --build . --target INSTALL --config Release
    - bin/click-tests --reporter junit --out win-catch2-junit.xml
  artifacts:
    paths:
      - oos/install
      - oos/bin
    when: always
    reports:
      junit: oos/win-catch2-junit.xml


build-test-x64-cpp-lib-windows:
  extends: .build-test-cpp-lib-windows
  variables:
    TARGET_ARCH: "x64"
    EXTRA_PARAMS: "-DBUILD_SHARED_LIBS=ON"

# ABB No longer needs win32, so disable and remove after 2024-06
# build-test-static-Win32-cpp-lib-windows:
#   tags:
#     - win32
#     - vs2019
#   extends: .build-test-cpp-lib-windows
#   variables:
#     TARGET_ARCH: "Win32"

# build-test-dynamic-Win32-cpp-lib-windows:
#   tags:
#     - win32
#     - vs2019
#   extends: .build-test-cpp-lib-windows
#   variables:
#     TARGET_ARCH: "Win32"
#     EXTRA_PARAMS: "-DBUILD_SHARED_LIBS=ON"

# publish-dynamic-Win32-cpp-lib-windows:
#   extends: .publish-cpp-lib-windows
#   variables:
#     PACKAGE_UPLOAD_NAME: click-win32
#   needs:
#     - job: build-test-dynamic-Win32-cpp-lib-windows
#       artifacts: true

.publish-cpp-lib-windows:
  extends: .run-in-docker
  stage: publish
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - find oos
    - PACKAGE_VERSION=$CI_COMMIT_TAG
    - PACKAGE_NAME=$PACKAGE_UPLOAD_NAME-$PACKAGE_VERSION.zip
    - echo Publishing $PACKAGE_NAME as ${PACKAGE_VERSION}/${PACKAGE_UPLOAD_NAME} and latest/${PACKAGE_UPLOAD_NAME}
    - zip -r $PACKAGE_NAME oos doc LICENSE README.md
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $PACKAGE_NAME "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/click/${PACKAGE_VERSION}/${PACKAGE_NAME}"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $PACKAGE_NAME "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/click/latest/${PACKAGE_NAME}"'
  only:
    - tags

publish-x64-cpp-lib-windows:
  extends: .publish-cpp-lib-windows
  variables:
    PACKAGE_UPLOAD_NAME: click-x64
  needs:
    - job: build-test-x64-cpp-lib-windows
      artifacts: true

push-main-to-github:
  extends: .run-in-docker
  stage: build
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - git remote add mirror git@github.com:Algoryx/click-mirror.git || echo remote mirror already exists.
    - eval "$(ssh-agent -s)"
    - chmod 0600 ${click_github_push_key} # Must be protected to add (and end with a newline)
    - ssh-add ${click_github_push_key}
    # CI_COMMIT_REF_NAME - The branch or tag name for which project is built
    - git push mirror refs/remotes/origin/${CI_COMMIT_REF_NAME}:refs/heads/${CI_COMMIT_REF_NAME}
  only:
    - main

push-tag-to-github:
  extends: .run-in-docker
  stage: build
  image: $CI_REGISTRY_IMAGE/docker-ci:${CI_IMAGE_TAG}
  script:
    - git remote add mirror git@github.com:Algoryx/click-mirror.git || echo remote mirror already exists.
    - eval "$(ssh-agent -s)"
    - chmod 0600 ${click_github_push_key} # Must be protected to add (and end with a newline)
    - ssh-add ${click_github_push_key}
    # CI_COMMIT_REF_NAME - The branch or tag name for which project is built
    - git push mirror ${CI_COMMIT_REF_NAME}
  only:
    - tags
