version: "3"
services:
  click:
    build:
      context: .
      dockerfile: Dockerfile.CI
    image: registry.algoryx.se/algoryx/external/click/docker-ci
    working_dir: "/click"
    command: ${CMD:-"bash"}
    volumes:
      - ../:/click
    ports:
      # Enable outside access to zmq server
      - "5555:5555"
