# Run with docker compose -f docker/docker-compose-pytest.yml run pytest

version: "3"
services:
  pytest:
    image: registry.algoryx.se/algoryx/external/click/docker-ci-agx:0.0.1
    build:  
      dockerfile: Dockerfile.CI-agx
    working_dir: "/click"
    # TODO: Below is outdated, update to use poetry
    command: bash -c \
      "cd agxclick && \
       poetry add --editable ../python-src && \
       echo RUN poetry run pytest && \
       bash"
    volumes:
      - ../:/click
