# Run with docker compose -f docker/docker-compose-pytest.yml run pytest

version: "3"
services:
  pytest:
    image: registry.algoryx.se/algoryx/external/agx-docker/agxbrick-minified:agx-2.32.0.0_agxbrick-0.5.2
    working_dir: "/click"
    command: bash -c \
      "pip3 install -r python-src/requirements-test.txt && \
       pip3 install -r python-src/requirements-publish.txt && \
       rm -rf python-src/dist agxClick/dist && \
       cd python-src && \
       python3 setup.py sdist bdist_wheel && \
       cd ../agxClick && \
       python3 setup.py sdist bdist_wheel && \
       cd .. && \
       pip3 install python-src/dist/pClick*whl && \
       pip3 install agxClick/dist/agxClick*whl && \
       echo RUN pytest agxClick && \
       bash"
    volumes:
      - ../:/click
