#include <fstream>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_all.hpp>
#include <Messaging.pb.h>
#include "testpaths.h"

using namespace std;
using namespace algoryx::click::protobuf;
// https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#top
using Catch::Matchers::Contains;
using Catch::Matchers::Equals;
using google::protobuf::Map;

SCENARIO("Protobuf sensormessage serialization from file", "[clicklib]" ) {

    GIVEN("A serialized sensormessage") {

        fstream input(TESTDATA_DIR + "sensormessage.bin", ios::in | ios::binary);
        REQUIRE(input);

        WHEN("creating sensormessage from bytes generated by python") {
            SensorMessage sensorMessage;
            REQUIRE(sensorMessage.ParseFromIstream(&input));

            THEN("it should contain robot1 sensor values") {

                REQUIRE(sensorMessage.objects().at("robot1").anglesensors().at(0) == 1.0);
                REQUIRE(sensorMessage.objects().at("robot1").anglevelocitysensors().at(0) == 2.0);
                REQUIRE(sensorMessage.objects().at("robot1").torquesensors().at(0) == 3.0);
                REQUIRE_THAT(sensorMessage.DebugString(), Catch::Matchers::StartsWith("messageType: SensorMessageType"));
//                REQUIRE_THAT(sensorMessage.DebugString(), Equals("SensorMessageType"));
            }

            THEN("it should contain box rpy") {

                Map<string, SensorMessage_Object> objects = sensorMessage.objects();
                using google::protobuf::RepeatedField;
                RepeatedField<double> vec = objects["box"].objectsensors()[1].rpy().arr();
                vector<double> actual(vec.begin(), vec.end());
                vector<double> expected = {4.0, 5.0, 6.0};
                REQUIRE(actual == expected);
            }
        }
    }
}
