#include <fstream>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_all.hpp>
#include "Messaging.pb.h"

using namespace std;
using namespace iam;
// https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#top
using Catch::Matchers::Contains;
using Catch::Matchers::Equals;
using google::protobuf::Map;

SCENARIO("sensormessage serialization", "[clicklib]" ) {

    GIVEN("A serialized sensormessage") {

        string sensorbinary = "../../testdata/sensormessage.bin";
        fstream input(sensorbinary, ios::in | ios::binary);
        REQUIRE(input);

        WHEN("creating sensormessage from bytes generated by python") {
            SensorMessage sensorMessage;
            REQUIRE(sensorMessage.ParseFromIstream(&input));

            THEN("it should contain robot1 sensor values") {

                Map<string, SensorMessage_Object> objects = sensorMessage.objects();
                Map<string, SensorMessage_Sensors> sensors = objects["robot1"].sensors();
                REQUIRE(sensors["joint1"].sensor()[0].angle() == 1.0);
                REQUIRE(sensors["joint1"].sensor()[1].anglevelocity() == 2.0);
                REQUIRE(sensors["joint1"].sensor()[2].torque() == 3.0);
                REQUIRE_THAT(sensorMessage.DebugString(), Catch::Matchers::StartsWith("messageType: SensorMessageType"));
//                REQUIRE_THAT(sensorMessage.DebugString(), Equals("SensorMessageType"));
            }

            THEN("it should contain box position") {

                Map<string, SensorMessage_Object> objects = sensorMessage.objects();
                using google::protobuf::RepeatedField;
                RepeatedField<double> vec = objects["box"].objectsensors()[0].rpy().arr();
                vector<double> actual(vec.begin(), vec.end());
                vector<double> expected = {4.0, 5.0, 6.0};
                REQUIRE(actual == expected);
            }
        }
    }
}
